config/routes.rb
Rails.application.routes.draw do
  root controller: 'users', action: 'show'
  resources :locations
  resources :resources do
    resources :availabilities, except: [:edit]
    member do
      get 'current'
    end
  end
  resources :availabilities, only: [] do
    collection do
      get 'all'
    end
  end
  resources :bookings, only: [:create, :destroy, :index] do
    collection do
      get 'help'
    end
  end
  resources :users do
    member do
      put 'update_permissions'
    end
    collection do
      get 'login'
      post 'login'
      post 'logout'
      post 'reset_api_key'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :availabilities, through: :bookings
  has_secure_token :api_key

  validates_uniqueness_of :username
  validates_presence_of :display_name
  validates_uniqueness_of :email, allow_nil: true

  after_update :delete_future_bookings

  scope :data, -> { pluck_to_hash(*DATA_FIELDS) }

  def active?
    self.admin || self.client
  end

  def hit_bookings_limit?
    return false if Rails.configuration.future_bookings.nil?

    current_count = self.bookings.current.count
    current_count -= 1 if current_count.positive? # one current booking does not count towards limit
    future_count = self.bookings.future.count
    current_count + future_count >= Rails.configuration.future_bookings
  end

  private

  DATA_FIELDS = %w[username display_name email id admin client read_only]

  def delete_future_bookings
    bookings.future.destroy_all if saved_change_to_client?(from: true, to: false)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def login
    if current_user.nil?
      user = User.find_by(username: login_params[:username])
      if user.nil? || !validate_user(user, login_params[:password])
        flash[:error] = t('views.users.login.invalid') if request.post?
        render :login, locals: { username: login_params[:username] }
      else
        session[:user_id] = user.id
        redirect_to root_path
      end
    else
      redirect_to root_path
    end
  end

  def logout
    clear_session
    redirect_to action: :login
  end

  def show
    @user ||= current_user
    if @user.client
      @calendar_data = format_calendar_data(@user.availabilities.data + Availability.bookable.data)
    end
    respond_to do |format|
      format.html
      format.json { render json: User.where(id: params[:id]).data.first }
    end
  end

  def index
    @data = User.all.data
    respond_to do |format|
      format.html
      format.json { render json: @data }
    end
  end

  def reset_api_key
    current_user.regenerate_api_key
    respond_to do |format|
      format.html { redirect_to action: :show }
      format.json { render json: { new_api_key: current_user.reload.api_key } }
    end
  end

  def update_permissions
    if @user.update(permissions_params)
      respond_to do |format|
        format.json { render json: @user, status: :ok }
      end
    end
  end

  private

  def login_params
    params.permit(:username, :password)
  end

  def create_update_params
    params.require(:user).permit(:username, :display_name, :email)
  end

  def permissions_params
    params.require(:user).permit(:admin, :client, :read_only)
  end

  def validate_user(user, password)
    return false if password.strip.blank? || !user.active?

    not_allowed_regexp = Regexp.new(/[\n\0]+/)
    return false if not_allowed_regexp.match(user.username) || not_allowed_regexp.match(password)

    pipe = IO.popen("'#{Rails.configuration.validation_script}'", 'w+') # quotes to avoid choking on spaces
    to_stdin = [user.username, password].join("\n")
    pipe.puts(to_stdin)
    pipe.close
    $?.exitstatus == 0
  end

  def set_attributes
    @user = User.find_by_id(params[:id])
  end

  protected

  def do_authorize
    action_name != 'login'
  end

  def implicit_authorization_target
    @user || current_user
  end
end

app/views/users/_form.html.erb
<%= form_with model: @user, local: true, class: 'create-update-form' do |f| %>
  <div class='form-input'>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class='form-input'>
    <%= f.label :display_name %>
    <%= f.text_field :display_name %>
  </div>
  <div class='form-input'>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= submit_tag %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render partial: 'form' %>

app/views/users/index.html.erb
<div class='index-header'>
  <h3><%= t('activerecord.models.user').pluralize %></h3>
  <% unless allowed_to?(:read_only?) %>
    <%= button_to t('shared.new', record: t('activerecord.models.user')), new_user_path, method: :get %>
  <% end %>
</div>
<table class='index-table'>
  <tr>
    <th><%= t('activerecord.attributes.user.username') %></th>
    <th><%= t('activerecord.attributes.user.display_name') %></th>
    <th><%= t('activerecord.attributes.user.email') %></th>
  </tr>
  <% @data.each do |row| %>
    <tr>
      <td><%= link_to row['username'], user_path(row['id']) %></td>
      <td><%= row['display_name'] %></td>
      <td><%= row['email'] %></td>
    </tr>
  <% end %>
</table>

app/views/users/login.html.erb
<div class='login-form-container'>
  <%= form_tag action: :login  do %>
    <% username ||= '' %>
    <%= text_field_tag 'username',
                       nil,
                       tabindex: 1,
                       placeholder: User.human_attribute_name(:username),
                       autocorrect: 'off',
                       autocapitalize: 'off',
                       autofocus: username == '',
                       value: username %>
    <%= password_field_tag 'password',
                           nil,
                           tabindex: 2,
                           placeholder: t('views.users.login.password'),
                           autofocus: username != '' %>
    <div class='submit'>
      <%= submit_tag t('views.users.login.log_in'),
                     data: { disable_with: t('views.users.login.logging_in') },
                     tabindex: 3 %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<%= render partial: 'form' %>

app/views/users/show.html.erb
<div class='model-container'>
  <div class='model-attributes'>
    <span><strong><%= t('activerecord.attributes.user.username') %></strong> <%= @user.username %></span>
    <span><strong><%= t('activerecord.attributes.user.display_name') %></strong> <%= @user.display_name %></span>
    <span><strong><%= t('activerecord.attributes.user.email') %></strong> <%= @user.email %></span>
    <% if allowed_to?(:admin?) && allowed_to?(:current_user_is_user?) %>
      <span><strong><%= t('activerecord.attributes.user.api_key') %></strong> <%= @user.api_key %></span>
    <% end %>
  </div>
  <div class='model-buttons'>
    <% if allowed_to?(:admin?) && allowed_to?(:current_user_is_user?) %>
      <div class='list-button'>
        <%= form_with url: reset_api_key_users_path do |_| %>
          <%= submit_tag t('views.users.show.reset_api_key') %>
        <% end %>
      </div>
    <% end %>
    <% unless allowed_to?(:read_only?) || !allowed_to?(:admin?) %>
      <div class='list-button'>
        <%= button_to t('shared.edit'), edit_user_path(@user.id), method: :get %>
      </div>
    <% end %>
  </div>
</div>
<% if @user.client %>
  <%= react_component 'Calendar', @calendar_data %>
<% end %>