config/routes.rb
Rails.application.routes.draw do
  root controller: 'users', action: 'show'
  resources :locations
  resources :resources do
    resources :availabilities, except: [:edit]
    member do
      get 'current'
    end
  end
  resources :availabilities, only: [] do
    collection do
      get 'all'
    end
  end
  resources :bookings, only: [:create, :destroy, :index] do
    collection do
      get 'help'
    end
  end
  resources :users do
    member do
      put 'update_permissions'
    end
    collection do
      get 'login'
      post 'login'
      post 'logout'
      post 'reset_api_key'
    end
  end
end

app/views/shared/_flash_message.html.erb
<% flash.each do |type, msg| %>
  <div class='<%= "flash #{type}" %>'>
    <%= msg %>
  </div>
<% end %>
<% flash.clear %>

app/views/shared/_navigation_bar.html.erb
<div>
  <ul class='navigation-bar'>
    <% unless @current_user.nil? || Rails.configuration.remote_user_auth %>
      <li><%= link_to t('shared.home'), '/' %></li>
    <%end %>
    <% if allowed_to?(:admin?) %>
      <li><%= link_to Resource.model_name.human.pluralize, resources_path %></li>
      <li><%= link_to Location.model_name.human.pluralize, locations_path %></li>
      <li><%= link_to User.model_name.human.pluralize, users_path %></li>
      <li><%= link_to t('views.users.show.all_bookings'), bookings_path %></li>
    <% end %>
    <% if allowed_to?(:client?) %>
      <li><%= link_to t('shared.help'), help_bookings_path %></li>
    <% end %>
    <% unless @current_user.nil? || Rails.configuration.remote_user_auth %>
      <li class='logout'><%= link_to t('shared.logout'), logout_users_path, method: :post %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_set_flash_messages.js.erb
<% flash.each do |type, message| %>
  $('#flash-<%= type %>').html('<%= message %>')
<% end %>