config/routes.rb
Rails.application.routes.draw do
  root controller: 'users', action: 'show'
  resources :locations
  resources :resources do
    resources :availabilities, except: [:edit]
    member do
      get 'current'
    end
  end
  resources :availabilities, only: [] do
    collection do
      get 'all'
    end
  end
  resources :bookings, only: [:create, :destroy, :index] do
    collection do
      get 'help'
    end
  end
  resources :users do
    member do
      put 'update_permissions'
    end
    collection do
      get 'login'
      post 'login'
      post 'logout'
      post 'reset_api_key'
    end
  end
end

app/views/resources/_form.html.erb
<%= form_with model: @resource, local: true, class: 'create-update-form' do |f| %>
  <div class='form-input'>
    <%= f.label :resource_type %>
    <%= f.text_field :resource_type %>
  </div>
  <div class='form-input'>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class='form-input'>
    <%= f.label :location %>
    <%= f.select :location_id, options_for_select(Location.pluck(:name, :id), @resource.location&.id) %>
  </div>
  <div>
    <%= submit_tag %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<%= render partial: 'form' %>

app/views/resources/index.html.erb
<div class='index-header'>
  <h3><%= t('activerecord.models.resource').pluralize %></h3>
  <% unless allowed_to?(:read_only?) %>
    <%= button_to t('shared.new', record: t('activerecord.models.resource')), new_resource_path, method: :get %>
  <% end %>
</div>
<table class='index-table'>
  <tr>
    <th><%= t('activerecord.attributes.resources.name') %></th>
    <th><%= t('activerecord.attributes.resources.type') %></th>
    <th><%= t('activerecord.models.location') %></th>
  </tr>
  <% @data.each do |row| %>
    <tr>
      <td><%= link_to row['name'], resource_path(row['resources.id']) %></td>
      <td><%= row['resource_type'] %></td>
      <td><%= link_to row['locations.name'], location_path(row['locations.id']) %></td>
    </tr>
  <% end %>
</table>

app/views/resources/new.html.erb
<%= render partial: 'form' %>

app/views/resources/show.html.erb
<div class='model-container'>
  <div class='model-attributes'>
    <span><strong><%= t('activerecord.attributes.resources.name') %></strong> <%= @resource.name %></span>
    <span><strong><%= t('activerecord.attributes.resources.type') %></strong> <%= @resource.resource_type %></span>
    <span><strong>
      <%= t('activerecord.models.location') %></strong>
      <%= link_to @resource.location.name, location_path(@resource.location.id) %>
    </span>
  </div>
  <div class='model-buttons'>
    <% unless allowed_to?(:read_only?) || !allowed_to?(:admin?) %>
      <div><%= button_to t('shared.edit'), edit_resource_path(@resource.id), method: :get %></div>
      <div>
        <%= form_with model: @resource, method: 'DELETE', local: true do %>
          <%= submit_tag t('shared.delete'), data: { confirm: t('views.resource.show.delete_confirm') } %>
        <% end %>
      </div>
      <div>
        <%= button_to t('shared.new', record: t('activerecord.models.availability')),
                      new_resource_availability_path(@resource.id), method: :get %>
      </div>
    <% end %>
  </div>
</div>
<% if allowed_to?(:admin?) %>
  <%= react_component 'Calendar', @calendar_data %>
<% end %>