config/routes.rb
Rails.application.routes.draw do
  root controller: 'users', action: 'show'
  resources :locations
  resources :resources do
    resources :availabilities, except: [:edit]
    member do
      get 'current'
    end
  end
  resources :availabilities, only: [] do
    collection do
      get 'all'
    end
  end
  resources :bookings, only: [:create, :destroy, :index] do
    collection do
      get 'help'
    end
  end
  resources :users do
    member do
      put 'update_permissions'
    end
    collection do
      get 'login'
      post 'login'
      post 'logout'
      post 'reset_api_key'
    end
  end
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :resources, dependent: :destroy

  validates_uniqueness_of :name
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def show
    if allowed_to?(:admin?)
      data = Availability.joins(resource: :location)
                         .where('locations.id': @location)
                         .data
      @calendar_data = format_calendar_data(data)
    end
    respond_to do |format|
      format.html
      format.json { render json: @location.to_json }
    end
  end

  def index
    @data = Location.pluck_to_hash(*%w[name description id])
    respond_to do |format|
      format.html
      format.json { render json: @data }
    end
  end

  private

  def create_update_params
    params.require(:location).permit(:name, :description)
  end

  def set_attributes
    @location = Location.find_by_id(params[:id])
  end

  def implicit_authorization_target
    @location || Location
  end
end

app/views/locations/_form.html.erb
<%= form_with model: @location, local: true, class: 'create-update-form' do |f| %>
  <div class='form-input'>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class='form-input'>
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= submit_tag %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<%= render partial: 'form' %>

app/views/locations/index.html.erb
<div class='index-header'>
  <h3><%= t('activerecord.models.location').pluralize %></h3>
  <% unless allowed_to?(:read_only?) %>
    <%= button_to t('shared.new', record: t('activerecord.models.location')), new_location_path, method: :get %>
  <% end %>
</div>
<table class='index-table'>
  <tr>
    <th><%= t('activerecord.attributes.location.name') %></th>
    <th><%= t('activerecord.attributes.location.description') %></th>
  </tr>
  <% @data.each do |row| %>
    <tr>
      <td><%= link_to row['name'], location_path(row['id']) %></td>
      <td><%= row['description'] %></td>
    </tr>
  <% end %>
</table>

app/views/locations/new.html.erb
<%= render partial: 'form' %>

app/views/locations/show.html.erb
<div class='model-container'>
  <div class='model-attributes'>
    <span><strong><%= t('activerecord.attributes.location.name') %></strong> <%= @location.name %></span>
    <span><strong><%= t('activerecord.attributes.location.description') %></strong> <%= @location.description %></span>
  </div>
  <div class='model-buttons'>
    <% unless allowed_to?(:read_only?) || !allowed_to?(:admin?) %>
      <div><%= button_to t('shared.edit'), edit_location_path(@location.id), method: :get %></div>
      <div>
        <%= form_with model: @location, method: 'DELETE', local: true do %>
          <%= submit_tag t('shared.delete'), data: { confirm: t('views.location.show.delete_confirm') } %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<% if allowed_to?(:admin?) %>
  <%= react_component 'Calendar', @calendar_data %>
<% end %>